name: Continuous deployment
on: push
jobs:
  install-test:
    name: Install dependencies and test
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository for continuous integration
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install && npm install --dev
    - name: Test
      run: npm run test